server:  
  port: 8761

eureka:
  instance:
    hostname: localhost

  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
        enabled:true

    
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  boot:
    admin:
      context-path: /admin








eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
producer:
  ribbon:
    ServerListRefreshInterval: 5000
ribbon:
  IsSecure: false
  
  logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG