info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
#  shutdown:
#    enabled: true
#  health:
#    sensitive: false
  

zuul:
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 600000
  ignoredServices: '*'
  prefix: /api
  routes:
    webservices-api: 
      path: /web/**
      serviceId: webservices-api
    product-api:
      path: /prod/**   
      serviceId: product-api        

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
      
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG


